# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Setting vagrant box from https://atlas.hashicorp.com/search. 
  config.vm.box = "ubuntu-trusty64-gui"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://atlas.hashicorp.com/chad-thompson/boxes/ubuntu-trusty64-gui/versions/1.0/providers/virtualbox.box"

  # VirtualBox Provider-specific configuration
   config.vm.provider "virtualbox" do |vb|
  #	  # Setting name of VM
		vb.name="omen+"
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #	  # Disable USB controller
	 vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
     
  
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end


  # Enable provisioning with a shell script to install packages and other configuration
   config.vm.provision :shell do |sh|
     sh.path= "install.sh"
   end
end